import Head from 'next/head';
import Header from '../Header'; 


const Page1 = () => {

  return (

    <div>

      <Head>
        <title>Page 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />


      <div className="text-center bg-white text-black p-5 min-h-screen pt-16">

        <h1 className="text-2xl md:text-3xl lg:text-4xl font-bold pb-8 md:pb-12 lg:pb-16"> Trusted and used by many organizations Worldwide. </h1>


        <div className="flex flex-wrap justify-center gap-4 md:gap-6 lg:gap-10 pt-10">
          <img src="./page1/p1.1.png" alt="Image 1" className="w-20 sm:w-28 md:w-32 lg:w-40" />
          <img src="./page1/p1.2.png" alt="Image 2" className="w-20 sm:w-28 md:w-32 lg:w-40" />
          <img src="./page1/p1.3.png" alt="Image 3" className="w-20 sm:w-28 md:w-32 lg:w-40" />
          <img src="./page1/p1.4.png" alt="Image 4" className="w-20 sm:w-28 md:w-32 lg:w-40" />
          <img src="./page1/p1.5.png" alt="Image 5" className="w-20 sm:w-28 md:w-32 lg:w-40" />
          <img src="./page1/p1.6.png" alt="Image 6" className="w-20 sm:w-28 md:w-32 lg:w-40" />
        </div>


      <h1 className="pt-40 font-bold text-base" style={{ fontSize: '40px' }}>Get To Know V.connct Webinar</h1>

      <p className="pt-7">Explore the seamies flow of v.connct webinars, ensuring a smoth experience for both host and participants.</p>

      <div className="flex justify-center space-x-4 pt-10 space-x-20">

          <div className="">

            <img src="./page1/p1.7.png" alt="Image 1" className="w-full h-auto md:w-80 md:h-200" />
            <img src="./page1/p1.8.png" alt="Image 2" className="w-full h-auto md:w-80 md:h-50 mt-4 md:mt-0" />

          </div>

          <div className="">

            <img src="./page1/p1.9.png" alt="Image 3" className="w-full h-auto md:w-80 md:h-50" />

          </div>

          <div className="">

            <img src="./page1/p1.10.png" alt="Image 4" className="w-full h-auto md:w-80 md:h-50" />
            <img src="./page1/p1.11.png" alt="Image 5" className="w-full h-auto md:w-80 md:h-50 mt-4 md:mt-0" />
            
          </div>

      </div>

      <button className="mt-15 ml-4 p-5 border border-gray-400 font-bold rounded-2xl cursor-pointer hover:bg-black hover:text-white"> Plan & Pricing </button>

      </div>
    </div>
  );
};

export default Page1;
