import Head from 'next/head';
import Header from '../Header'; 


const Page2 = () => {

  const boxes = [

    { imgSrc: '/page2/p2.1.png', header: 'User-Friendly Interface', paragraph: 'Navigate Effortlessly Through Our User-Friendly Interface.' },
    { imgSrc: '/page2/p2.3.png', header: 'Comprehensive Features', paragraph: 'Enjoy a wide array of features. Tailor each webinar to your unique needs.' },
    { imgSrc: '/page2/p2.5.png', header: 'Up to 5000 Participants', paragraph: 'Host anything from intimate seminars to grand conferences.' },
    { imgSrc: '/page2/p2.2.png', header: 'Live Stream Capabilities', paragraph: 'Connect with participants globally in real-time with our live streaming option.' },
    { imgSrc: '/page2/p2.4.png', header: '30-Hour Webinar Duration', paragraph: 'Enjoy webinar durations for those in-depth discussions and comprehensive sessions.' },
    { imgSrc: '/page2/p2.6.png', header: 'Cloud Recording Storage', paragraph: 'Benefit from our cloud recording to ensure you never miss a crucial detail.' },

  ];


  return (

    <div>
      <Head>
        <title>Page 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Header />


      <div className="text-center bg-black text-black  p-5 pt-16">

        <h1 className="text-5xl text-white font-bold pb-16">Why Choose V.connct Webinar?</h1>
          
        <div className="p-10 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">

            {boxes.map((box, index) => (

              <div key={index} className="border-2 bg-black shadow-lg rounded p-4 flex flex-col items-start text-left">

                  <img src={box.imgSrc} alt={box.header} className="mb-4 w-20 h-20 object-cover" style={{ backgroundColor: '#1e293b' }} />

                  <h2 className="text-2xl text-white font-bold mb-2">{box.header}</h2>

                  <p className="text-lg text-white">{box.paragraph}</p>

              </div>

            ))}

        </div>

          <button className="w-56 text-2xl mt-20 mb-20 ml-4 p-5 border border-gray-400 bg-white rounded-2xl cursor-pointer hover:bg-yellow-500 hover:text-black">Plan & Pricing </button>

        </div>

          <div className="border border-black" style={{ backgroundColor: '#fed7aa' }}>

            <div className="mt-10 mb-12 border border-black text-black rounded-2xl shadow-lg p-4 max-w-7xl mx-auto" style={{ backgroundColor: '#ffffff' }}>

              <h1 className="mt-5 text-3xl font-bold mb-4 rounded-md p-2" style={{ backgroundColor: '#ffffff' }}>Need Help! Webinar Documentation</h1>

              <p className="text-lg mb-2 rounded-md p-2" style={{ backgroundColor: '#ffffff' }}>Need production help? Webinar Documentation has you covered. We can help ensure your next webinar goes off without a hitch.</p>

              <a href="#" className="text-lg rounded-md p-2 pb-2" style={{ backgroundColor: '#ffffff', textDecoration: 'underline' }}>Help Center   ⭢</a> 
              
           </div>
      </div>


    </div>
  );
};

export default Page2;
