import Head from 'next/head';
import Header from './Header';


export default function Home() {
  return (

    <div>
      
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className="text-center bg-white text-black bg-opacity-80 p-5 h-[calc(110vh-70px)] pt-16">
        

            <h1 className="text-5xl font-bold pb-16">All-in-One Solution For Effortless Webinar Hosting</h1>

            <p className="text-xl"> Create immersive live webinar experiences with everything you need. Join industry experts for a transformative learning experience and gain the audience you need. </p>

            <div className="pt-8">

              <button className="mr-4 ml-4 p-4 border border-gray-400 bg-white text-black-500 rounded-lg cursor-pointer hover:bg-yellow-500 hover:text-black hover:font-bold"> Plans & Pricing </button>

              <button className="ml-4 p-4 border border-gray-400 bg-white text-black-500 rounded-lg cursor-pointer hover:bg-yellow-500 hover:text-black hover:font-bold"> Contact Us </button>

              <img src="/page1.png" alt="Logo" className="mx-auto mt-8 w-[1300px] h-[700px] pt-10" />

            </div>


       </div>

      </div>
  );
}
