import Head from 'next/head';
import Header from '../Header'; 


const Page3 = () => {

  return (

    <div>
      <Head>
        <title>Page 3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="bg-white text-black p-5 h-auto pt-16">

        <section className="faqs">

          <h1 className="text-center text-5xl font-bold pb-16">FAQs</h1>

          <div className="p-12 text-2xl space-y-7 text-left">
            
            <FaqItem 
              question="How many participants can I host in a webinar?" 
              answer="v.connect supports up to 5000 participants, offering scalability for events of any size." 
            />

            <FaqItem 
              question="Can I live stream my webinars?" 
              answer="Absolutely! Enjoy the benefits of reaching a wider audience in real-time." 
            />

            <FaqItem 
              question="How long can a webinar last?" 
              answer="Webinars can extend up to 30 hours, providing flexibility for various event durations." 
            />

            <FaqItem 
              question="Are email notifications automated?" 
              answer="Yes, v.connect sends automated emails for registration, start, and end times." 
            />

          </div>

        </section>

      </main>

      <section className="text-center bg-black py-20">

        <h1 className="font-bold text-7xl text-white">Ready To Elevate Your Website?</h1>

        <button className="w-56 text-2xl mt-20 mb-20 p-5 border border-gray-400 bg-white rounded-2xl cursor-pointer hover:bg-yellow-500 hover:text-black"> Buy Now </button>

      </section>

    </div>
  );
};

const FaqItem = ({ question, answer }) => (

  <div className="pb-2 border-b border-black flex items-center justify-between">

    <div>

      <p>{question}</p>
      <p className="pt-2">{answer}</p>

    </div>

    <span className="ml-auto text-yellow-500">&#9660;</span>

  </div>
  
);


export default Page3;
